
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-s3g
  labels:
    app: ozone
    component: s3g
spec:
  selector:
    matchLabels:
      app: ozone
      component: s3g
  serviceName: ozone-s3g
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: s3g
    spec:
      containers:
      - name: s3g
        image: elek/ozone-dev:66d85f303
        args:
        - ozone
        - s3g
        volumeMounts:
        - name: data
          mountPath: /data
        - name: btm
          mountPath: /opt/btm
        envFrom:
        - configMapRef:
            name: ozone-config
        env:
        - name: HADOOP_OPTS
          value: -javaagent:/opt/byteman/lib/byteman.jar=script:/opt/btm/hcfs-write.btm
      volumes:
      - name: data
        emptyDir: {}
      - name: btm
        configMap:
          name: btm
          defaultMode: 493
