
apiVersion: batch/v1
kind: Job
metadata:
  name: test-runner
spec:
  template:
    metadata:
      name: test-runner
    spec:
      restartPolicy: Never
      containers:
      - image: flokkr/spark-hadoop3:3.0.0
        name: test
        args:
        - sleep
        - infinity
      