
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 999
      containers:
      - name: sleep
        image: elek/ozone-build:20191106-1
        args:
        - sleep
        - "1000000000"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
            readOnly: false
      volumes:
        - name: docker-sock
          hostPath:
            path: "/var/run/docker.sock"
            type: File