
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/component: server
  name: docker-registry
spec:
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/component: server
  type: NodePort
