
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scm
  labels:
    app: ozone
    component: scm
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: scm
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: scm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9876"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: elek/ozone:20191108-3
        args:
        - ozone
        - scm
        - --init
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: data
          mountPath: /data
      containers:
      - name: scm
        image: elek/ozone:20191108-3
        args:
        - ozone
        - scm
        envFrom:
        - configMapRef:
            name: config
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: JAEGER_SAMPLER_TYPE
          value: probabilistic
        - name: JAEGER_SAMPLER_PARAM
          value: "0.01"
        - name: JAEGER_AGENT_HOST
          value: jaeger-0.jaeger
      volumes:
      - name: data
        emptyDir: {}
