apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  annotations:
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: ve0219.halxg.cloudera.com
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
