
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-public
  labels:
    app: flink
    component: jobmanager
spec:
  ports:
  - port: 8081
    name: ui
  selector:
    app: flink
    component: jobmanager
  type: NodePort
