
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    component: taskmanager
spec:
  ports:
  - port: 8081
    name: ui
  clusterIP: None
  selector:
    app: flink
    component: taskmanager
