
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager-public
  labels:
    app: flink
    component: taskmanager
spec:
  ports:
  - port: 8081
    name: ui
  selector:
    app: flink
    component: taskmanager
  type: NodePort
