
apiVersion: batch/v1
kind: Job
metadata:
  name: test-runner
spec:
  template:
    metadata:
      name: test-runner
    spec:
      restartPolicy: Never
      containers:
      - image: flokkr/hadoop:latest
        name: test
        args:
        - /opt/tests/teragen.sh
        volumeMounts:
        - name: tests
          mountPath: /opt/tests
      volumes:  
      - name: tests
        configMap:
         name: teragen-testscript
         defaultMode: 0755
      
