
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/data/2"]
            }
            ]
    }
