
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-datanode
  labels:
    app: ozone
    component: datanode
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  serviceName: ozone-datanode
  replicas: 3
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9882"
        prometheus.io/path: /prom
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - datanode
              - key: app
                operator: In
                values:
                - ozone
            topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      containers:
      - name: datanode
        image: flokkr/ozone
        args:
        - ozone
        - datanode
        volumeMounts:
        - name: data
          mountPath: /data
        - name: java-async-profiler
          mountPath: /opt/java-async-profiler
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: java-async-profiler
        emptyDir: {}
      initContainers:
      - name: java-async-profiler-copy
        image: elek/java-async-profiler
        command:
        - bash
        - -c
        - cp -r /opt/java-async-profiler/* /tmp/java-async-profiler/
        volumeMounts:
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
