
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-om
  labels:
    app: ozone
    component: om
spec:
  selector:
    matchLabels:
      app: ozone
      component: om
  serviceName: ozone-om
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: om
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9874"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: flokkr/ozone
        args:
        - ozone
        - om
        - --init
        env:
        - name: WAITFOR
          value: ozone-scm-0.ozone-scm:9876
        volumeMounts:
        - name: data
          mountPath: /data
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
        envFrom:
        - configMapRef:
            name: ozone-config
      - name: java-async-profiler-copy
        image: elek/java-async-profiler
        command:
        - bash
        - -c
        - cp -r /opt/java-async-profiler/* /tmp/java-async-profiler/
        volumeMounts:
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
      containers:
      - name: om
        image: flokkr/ozone
        args:
        - ozone
        - om
        volumeMounts:
        - name: data
          mountPath: /data
        - name: java-async-profiler
          mountPath: /opt/java-async-profiler
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: java-async-profiler
        emptyDir: {}
