
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-scm
  labels:
    app: ozone
    component: scm
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: ozone-scm
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: scm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9876"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: flokkr/ozone
        args:
        - ozone
        - scm
        - --init
        volumeMounts:
        - name: data
          mountPath: /data
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
        envFrom:
        - configMapRef:
            name: ozone-config
      - name: java-async-profiler-copy
        image: elek/java-async-profiler
        command:
        - bash
        - -c
        - cp -r /opt/java-async-profiler/* /tmp/java-async-profiler/
        volumeMounts:
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
      containers:
      - name: scm
        image: flokkr/ozone
        args:
        - ozone
        - scm
        volumeMounts:
        - name: data
          mountPath: /data
        - name: java-async-profiler
          mountPath: /opt/java-async-profiler
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      - name: java-async-profiler
        emptyDir: {}
