
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freon
  labels:
    app: ozone
    component: freon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ozone
      component: freon
  template:
    metadata:
      labels:
        app: ozone
        component: freon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9884"
        prometheus.io/path: /prom
    spec:
      containers:
      - name: ozone
        image: flokkr/ozone
        args:
        - ozone
        - freon
        - dcg
        - --size=10240
        - -t40
        - -n100000
        env: []
        envFrom:
        - configMapRef:
            name: ozone-config
