
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: loki
spec:
  ports:
  - name: loki
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: loki
