
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: loki
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: loki
  serviceName: loki
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: loki
      annotations: null
    spec:
      containers:
      - name: loki
        args:
        - -config.file=/etc/loki/config.yaml
        image: grafana/loki
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/loki
          name: loki-config
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
