
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-datanode
  labels:
    app: ozone
    component: datanode
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  serviceName: ozone-datanode
  replicas: 6
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9882"
        prometheus.io/path: /prom
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - datanode
            topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      containers:
      - name: freon
        image: elek/ozone-dev:HDDS-2717-cmdw
        args:
         - /opt/tester/test.sh
        volumeMounts:
        - name: script
          mountPath: /opt/tester/test.sh
          subPath: test.sh
        - name: data
          mountPath: /data
        - name: storage
          mountPath: /storage
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: storage
        emptyDir: {}
#            medium: Memory
      - name: data
        emptyDir:
           medium: Memory
      - name: script
        configMap:
           name: ozone-testscript
           defaultMode: 0755
