
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: hdfs-namenode
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: hdfs
      component: namenode
  template:
    metadata:
      labels:
        app: hdfs
        component: namenode
    spec:
      initContainers:
      - name: hdfs-init
        image: flokkr/hadoop
        args:
        - hadoop
        - version
        env:
        - name: ENSURE_NAMENODE_DIR
          value: /data/namenode
        envFrom:
        - configMapRef:
            name: hdfs-config
        volumeMounts:
        - name: data
          mountPath: /data
        - name: byteman
          mountPath: /opt/byteman
      - name: byteman-copy
        image: elek/byteman
        command:
        - bash
        - -c
        - cp -r /tmp/byteman /opt/
        volumeMounts:
        - name: byteman
          mountPath: /opt/byteman
      containers:
      - name: hdfs-namenode
        image: flokkr/hadoop
        args:
        - hdfs
        - namenode
        envFrom:
        - configMapRef:
            name: hdfs-config
        volumeMounts:
        - name: data
          mountPath: /data
        - name: byteman
          mountPath: /opt/byteman
        - name: btm
          mountPath: /opt/btm
        env:
        - name: BYTEMAN_HOME
          value: /opt/byteman
        - name: HADOOP_OPTS
          value: -javaagent:/opt/byteman/lib/byteman.jar=script:/opt/btm/hcfs-write.btm
      volumes:
      - name: data
        emptyDir: {}
      - name: byteman
        emptyDir: {}
      - name: btm
        configMap:
          name: btm
          defaultMode: 493
