
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-om
  labels:
    app: ozone
    component: om
spec:
  selector:
    matchLabels:
      app: ozone
      component: om
  serviceName: ozone-om
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: om
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9874"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: localhost:32482/elek/ozone-dev:bbf5d5e
        args:
        - ozone
        - om
        - --init
        env:
        - name: WAITFOR
          value: ozone-scm-0.ozone-scm:9876
        volumeMounts:
        - name: data
          mountPath: /data
        - name: byteman
          mountPath: /opt/byteman
        envFrom:
        - configMapRef:
            name: ozone-config
      - name: byteman-copy
        image: elek/byteman
        command:
        - bash
        - -c
        - cp -r /tmp/byteman /opt/
        volumeMounts:
        - name: byteman
          mountPath: /opt/byteman
      containers:
      - name: om
        image: localhost:32482/elek/ozone-dev:bbf5d5e
        args:
        - ozone
        - om
        volumeMounts:
        - name: data
          mountPath: /data
        - name: byteman
          mountPath: /opt/byteman
        envFrom:
        - configMapRef:
            name: ozone-config
        env:
        - name: BYTEMAN_HOME
          value: /opt/byteman
      volumes:
      - name: data
        emptyDir:
          medium: Memory
      - name: byteman
        emptyDir: {}
