
kind: Service
apiVersion: v1
metadata:
  name: prometheus-public
  labels:
    app: prometheus
    component: server
spec:
  selector:
    app: prometheus
    component: server
  ports:
  - protocol: TCP
    port: 9090
  type: NodePort
