
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-om
  labels:
    app: ozone
    component: om
spec:
  selector:
    matchLabels:
      app: ozone
      component: om
  serviceName: ozone-om
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: om
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9874"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: elek/ozone:0.5.0-rc2-beta
        args:
        - ozone
        - om
        - --init
        env:
        - name: WAITFOR
          value: ozone-scm-0.ozone-scm:9876
        volumeMounts:
        - name: data
          mountPath: /data
        - name: storage
          mountPath: /data/storage
        envFrom:
        - configMapRef:
            name: ozone-config
      containers:
      - name: om
        image: elek/ozone:0.5.0-rc2-beta
        args:
        - ozone
        - om
        volumeMounts:
        - name: data
          mountPath: /data
        - name: storage
          mountPath: /data/storage
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      nodeSelector:
        partition: lower
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 2Gi
