
apiVersion: v1
kind: ConfigMap
metadata:
  name: ozone-config
data:
  CORE-SITE.xml_fs.AbstractFileSystem.o3fs.impl: org.apache.hadoop.fs.ozone.OzFs
  OZONE-SITE.XML_hdds.datanode.dir: /data/storage
  OZONE-SITE.XML_ozone.scm.datanode.id.dir: /data
  OZONE-SITE.XML_ozone.metadata.dirs: /data/metadata
  OZONE-SITE.XML_ozone.scm.block.client.address: ozone-scm-0.ozone-scm
  OZONE-SITE.XML_ozone.om.address: ozone-om-0.ozone-om
  OZONE-SITE.XML_ozone.scm.client.address: ozone-scm-0.ozone-scm
  OZONE-SITE.XML_ozone.scm.names: ozone-scm-0.ozone-scm
  OZONE-SITE.XML_ozone.enabled: "true"
  OZONE-SITE.XML_hdds.scm.safemode.min.datanode: "3"
  LOG4J.PROPERTIES_log4j.rootLogger: INFO, stdout
  LOG4J.PROPERTIES_log4j.appender.stdout: org.apache.log4j.ConsoleAppender
  LOG4J.PROPERTIES_log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
  LOG4J.PROPERTIES_log4j.appender.stdout.layout.ConversionPattern: '%d{yyyy-MM-dd
    HH:mm:ss} %-5p %c{1}:%L - %m%n'
  MAPRED-SITE.XML_mapreduce.application.classpath: /opt/hadoop/share/hadoop/mapreduce/*:/opt/hadoop/share/hadoop/mapreduce/lib/*:/opt/ozonefs/hadoop-ozone-filesystem-lib-current-0.5.0-SNAPSHOT.jar
  HADOOP_OPTS: -server -XX:ParallelGCThreads=8 -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=70
    -XX:+UseCMSInitiatingOccupancyOnly
  OZONE-SITE.XML_ozone.om.handler.count.key: "250"
  OZONE-SITE.XML_ozone.scm.handler.count.key: "250"
  OZONE-SITE.XML_dfs.ratis.client.request.retry.interval: 15s
  OZONE-SITE.XML_hdds.ratis.raft.server.write.element-limit: "4096"
  OZONE-SITE.XML_hdds.datanode.df.refresh.period: 60m
  OZONE-SITE.XML_hdds.datanode.du.factory.classname: org.apache.hadoop.hdds.fs.DedicatedDiskSpaceUsageFactory
