
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-s3g
  labels:
    app: ozone
    component: s3g
spec:
  selector:
    matchLabels:
      app: ozone
      component: s3g
  serviceName: ozone-s3g
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: s3g
    spec:
      containers:
      - name: s3g
        image: elek/ozone:0.5.0-rc2-beta
        args:
        - ozone
        - s3g
        volumeMounts:
        - name: data
          mountPath: /data
        - name: storage
          mountPath: /data/storage
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir: {}
      nodeSelector:
        partition: lower
  volumeClaimTemplates:
  - metadata:
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 2Gi
