
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/component: server
data:
  config.yml: |-
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
