
apiVersion: batch/v1
kind: Job
metadata:
  name: test-runner
spec:
  backoffLimit: 0
  template:
    metadata:
      name: test-runner
    spec:
      restartPolicy: Never
      containers:
      - image: elek/spark-samples@sha256:d440143e1852998b05472c210441e105cb68f8ba010f69948995cd7ddc009743
        name: test
        args:
        - sleep
        - infinity
        volumeMounts:
          - mountPath: /opt/testscripts
            name: testscripts
          - mountPath: /opt/btm
            name: btm
      restartPolicy: Never
      volumes:
        - name: testscripts
          configMap:
              name: testscripts
              defaultMode: 0755
        - name: btm
          configMap:
             name: btm
