
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-nodemanager
  labels:
    app: yarn
    component: nodemanager
spec:
  serviceName: yarn-nodemanager
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: yarn
      component: nodemanager
  template:
    metadata:
      labels:
        app: yarn
        component: nodemanager
    spec:
      containers:
      - name: yarn-nodemanager
        image: flokkr/hadoop
        args:
        - yarn
        - nodemanager
        env:
        - name: WAITFOR
          value: yarn-resourcemanager-0.yarn-resourcemanager:8031
        - name: HADOOP_CLASSPATH
          value: /opt/ozonefs/hadoop-ozone-filesystem.jar
        envFrom:
        - configMapRef:
            name: yarn-config
        - configMapRef:
            name: ozone-client-config
        - configMapRef:
            name: ozone-config
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozonefs
          mountPath: /opt/ozonefs
      volumes:
      - name: data
        emptyDir: {}
      - name: ozonefs
        emptyDir: {}
      initContainers:
      - name: ozonefscopy
        image: elek/ozone-dev:4d293d124
        command:
        - bash
        - -c
        - cp share/ozone/lib/hadoop-ozone-filesystem-hadoop3-*.jar /opt/ozonefs/hadoop-ozone-filesystem.jar
        volumeMounts:
        - name: ozonefs
          mountPath: /opt/ozonefs
        envFrom:
        - configMapRef:
            name: ozone-client-config
