
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-datanode
  labels:
    app: ozone
    component: datanode
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  serviceName: ozone-datanode
  replicas: 6
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9882"
        prometheus.io/path: /prom
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - datanode
            topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      restartPolicy: Never
      containers:
      - name: datanode
        image: elek/ozonedev:20200206-1
        args:
        - ozone
        - datanode
        volumeMounts:
        - name: data
          mountPath: /data
        envFrom:
        - configMapRef:
            name: ozone-config
      volumes:
      - name: data
        emptyDir:
          medium: Memory
