apiVersion: v1
kind: ConfigMap
metadata:
  name: ozone-config
data:
  OZONE-SITE.XML_dfs.ratis.leader.election.minimum.timeout.duration: 2d
  OZONE_DATANODE_STANDALONE_TEST: follower
  HADOOP_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/heap.hprof 
  OZONE-SITE.XML_hdds.datanode.dir: /data/storage
  OZONE-SITE.XML_ozone.scm.datanode.id.dir: /data
  OZONE-SITE.XML_ozone.metadata.dirs: /data/metadata
  OZONE-SITE.XML_ozone.scm.block.client.address: ozone-scm-0.ozone-scm
  OZONE-SITE.XML_ozone.om.address: ozone-om-0.ozone-om
  OZONE-SITE.XML_ozone.scm.client.address: ozone-scm-0.ozone-scm
  OZONE-SITE.XML_ozone.scm.names: ozone-scm-0.ozone-scm
  LOG4J.PROPERTIES_log4j.rootLogger: INFO, stdout
  LOG4J.PROPERTIES_log4j.appender.stdout: org.apache.log4j.ConsoleAppender
  LOG4J.PROPERTIES_log4j.appender.stdout.layout: org.apache.log4j.PatternLayout
  LOG4J.PROPERTIES_log4j.appender.stdout.layout.ConversionPattern: '%d{yyyy-MM-dd
    HH:mm:ss} %-5p %c{1}:%L - %m%n'
  OZONE-SITE.XML_hdds.profiler.endpoint.enabled: "true"
  ASYNC_PROFILER_HOME: /opt/profiler
