
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freon
  labels:
    app: ozone
    component: freon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ozone
      component: freon
  template:
    metadata:
      labels:
        app: ozone
        component: freon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9884"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: wait
        image: elek/ozone-dev:980b7cfb7
        args:
        - ozone
        - scmcli
        - safemode
        - wait
        env: []
        envFrom:
        - configMapRef:
            name: ozone-config
      containers:
      - name: ozone
        image: elek/ozone-dev:980b7cfb7
        args:
        - ozone
        - freon
        - --server
        - dcg
        - -n10000
        env: []
        envFrom:
        - configMapRef:
            name: ozone-config
