apiVersion: batch/v1
kind: Job
metadata:
  labels:
     app: ozone
     component: test
  name: test-runner
spec:
  template:
    metadata:
      labels:
         app: ozone
         component: test
      name: test-runner
    spec:
      restartPolicy: Never
      containers:
      - image: flokkr/ozone:latest
        name: test
        args:
        - /opt/tests/teragen.sh
      
