
apiVersion: batch/v1
kind: Job
metadata:
  name: test-runner
spec:
  backoffLimit: 0
  template:
    metadata:
      name: test-runner
    spec:
      restartPolicy: Never
      containers:
      - image: elek/spark-samples@sha256:d440143e1852998b05472c210441e105cb68f8ba010f69948995cd7ddc009743
        name: test
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: /opt/testscripts
          name: testscripts
        - mountPath: /opt/btm
          name: btm
        - name: ozonefs
          mountPath: /opt/ozonefs
        - name: java-async-profiler
          mountPath: /opt/java-async-profiler
        envFrom:
        - configMapRef:
            name: ozone-client-config
        env:
        - name: HADOOP_CLASSPATH
          value: /opt/ozonefs/hadoop-ozone-filesystem.jar
      volumes:
      - name: testscripts
        configMap:
          name: testscripts
          defaultMode: 493
      - name: btm
        configMap:
          name: btm
      - name: ozonefs
        emptyDir: {}
      - name: java-async-profiler
        emptyDir: {}
      initContainers:
      - name: ozonefscopy
        image: localhost:32482/elek/ozone-dev:bbf5d5e
        command:
        - bash
        - -c
        - cp share/ozone/lib/hadoop-ozone-filesystem-hadoop3-*.jar /opt/ozonefs/hadoop-ozone-filesystem.jar
        volumeMounts:
        - name: ozonefs
          mountPath: /opt/ozonefs
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
      - name: java-async-profiler-copy
        image: elek/java-async-profiler
        command:
        - bash
        - -c
        - cp -r /opt/java-async-profiler/* /tmp/java-async-profiler/
        volumeMounts:
        - name: java-async-profiler
          mountPath: /tmp/java-async-profiler
