
apiVersion: batch/v1
kind: Job
metadata:
  name: test-runner
spec:
  template:
    metadata:
      name: test-runner
    spec:
      restartPolicy: Never
      containers:
      - image: flokkr/spark-hadoop3:3.0.0
        name: test
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: /opt/testscripts
          name: testscripts
        - name: ozonefs
          mountPath: /opt/ozonefs
        envFrom:
        - configMapRef:
            name: ozone-client-config
        env:
        - name: HADOOP_CLASSPATH
          value: /opt/ozonefs/hadoop-ozone-filesystem-hadoop3.jar
      volumes:
      - name: testscripts
        configMap:
          name: testscripts
      - name: ozonefs
        emptyDir: {}
      initContainers:
      - name: ozonefscopy
        image: elek/ozone-dev:256db2a74
        command:
        - bash
        - -c
        - cp share/ozone/lib/hadoop-ozone-filesystem-hadoop3-*.jar /opt/ozonefs/hadoop-ozone-filesystem-hadoop3.jar
        volumeMounts:
        - name: ozonefs
          mountPath: /opt/ozonefs
