
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freon
  labels:
    app.kubernetes.io/component: ozone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ozone
      component: freon
  template:
    metadata:
      labels:
        app: ozone
        component: freon
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9884"
        prometheus.io/path: /prom
    spec:
      containers:
      - name: freon
        image: elek/ozone:20191108-1
        args:
        - ozone
        - freon
        - dcg
        - -n10000000
        env:
        - name: JAEGER_SAMPLER_TYPE
          value: probabilistic
        - name: JAEGER_SAMPLER_PARAM
          value: "0.01"
        - name: JAEGER_AGENT_HOST
          value: jaeger-0.jaeger
        envFrom:
        - configMapRef:
            name: config
