apiVersion: v1
kind: Service
metadata:
  name: perftest-fio
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
     app: perftest
     component: fio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: perftest-fio
  labels:
    app: perftest
    component: fio
spec:
  serviceName: perftest-fio
  selector:
    matchLabels:
      app: perftest
      component: fio
  replicas: 1
  template:
    metadata:
      labels:
        app: perftest
        component: fio
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - fio
            topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      containers:
      - name: fio
        image: flokkr/perftest
        args:
         - /opt/tester/test.sh
        volumeMounts:
        - name: script
          mountPath: /opt/tester/test.sh
          subPath: test.sh
        - name: data
          mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
      - name: script
        configMap:
           name: fio-testscript
           defaultMode: 0755
