
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-scm
  labels:
    app: ozone
    component: scm
spec:
  selector:
    matchLabels:
      app: ozone
      component: scm
  serviceName: ozone-scm
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: scm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9876"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: flokkr/ozone
        args:
        - ozone
        - scm
        - --init
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozonefs
          mountPath: /opt/ozonefs
        envFrom:
        - configMapRef:
            name: ozone-config
      - name: ozonefscopy
        image: elek/ozone-dev:latest
        command:
        - bash
        - -c
        - cp share/ozone/lib/hadoop-ozone-filesystem-hadoop3-*.jar /opt/ozonefs/hadoop-ozone-filesystem-hadoop3.jar
        volumeMounts:
        - name: ozonefs
          mountPath: /opt/ozonefs
      containers:
      - name: scm
        image: flokkr/ozone
        args:
        - ozone
        - scm
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozonefs
          mountPath: /opt/ozonefs
        envFrom:
        - configMapRef:
            name: ozone-config
        env:
        - name: HADOOP_CLASSPATH
          value: /opt/ozonefs/hadoop-ozone-filesystem-hadoop3.jar
      volumes:
      - name: data
        emptyDir: {}
      - name: ozonefs
        emptyDir: {}
