
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ozone-om
  labels:
    app: ozone
    component: om
spec:
  selector:
    matchLabels:
      app: ozone
      component: om
  serviceName: ozone-om
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: om
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9874"
        prometheus.io/path: /prom
    spec:
      initContainers:
      - name: init
        image: flokkr/ozone
        args:
        - ozone
        - om
        - --init
        env:
        - name: WAITFOR
          value: ozone-scm-0.ozone-scm:9876
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozonefs
          mountPath: /opt/ozonefs
        envFrom:
        - configMapRef:
            name: ozone-config
      - name: ozonefscopy
        image: elek/ozone-dev:latest
        command:
        - bash
        - -c
        - cp share/ozone/lib/hadoop-ozone-filesystem-hadoop3-*.jar /opt/ozonefs/hadoop-ozone-filesystem-hadoop3.jar
        volumeMounts:
        - name: ozonefs
          mountPath: /opt/ozonefs
      containers:
      - name: om
        image: flokkr/ozone
        args:
        - ozone
        - om
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ozonefs
          mountPath: /opt/ozonefs
        envFrom:
        - configMapRef:
            name: ozone-config
        env:
        - name: HADOOP_CLASSPATH
          value: /opt/ozonefs/hadoop-ozone-filesystem-hadoop3.jar
      volumes:
      - name: data
        emptyDir: {}
      - name: ozonefs
        emptyDir: {}
