name: test
on:
    push:
    schedule:
    - cron: 0 * * * *
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          - datanode-isolated-follower
          - chunk-manager-write
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - name: Install k3s
        run: curl -sfL https://get.k3s.io | sh -s - --docker
      - name: Copy kubeconfig
        run: |
            sudo mkdir ~/.kube
            sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
            sudo chown $(id -u) ~/.kube/config
      - name: Install flekszible
        run: |
           cd /tmp
           wget https://github.com/elek/flekszible/releases/download/v1.9.0/flekszible_1.9.0_Linux_x86_64.tar.gz -O - | tar -zx
           chmod +x flekszible
           sudo mv flekszible /usr/bin/flekszible
      - name: Run test
        run: |
          ./${{ matrix.name }}/test.sh
      - run: |
          kubectl get pod | tee ./${{ matrix.name }}/results/podslist.txt
          kubectl describe pod | tee ./${{ matrix.name }}/results/pods-describe.txt
          kubectl get pods -o go-template --template  '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}' -l app=ozone | xargs -n1 kubectl logs --tail=50 | tee ./${{ matrix.name }}/results/logs.txt
        if: always()
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}/results/
